# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2P\n\x0fKeyValueService\x12\x1b\n\x03Get\x12\x07.kv.Key\x1a\t.kv.Value\"\x00\x12 \n\x03Put\x12\x0c.kv.KeyValue\x1a\t.kv.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEY._serialized_start=16
  _KEY._serialized_end=34
  _VALUE._serialized_start=36
  _VALUE._serialized_end=58
  _KEYVALUE._serialized_start=60
  _KEYVALUE._serialized_end=98
  _EMPTY._serialized_start=100
  _EMPTY._serialized_end=107
  _KEYVALUESERVICE._serialized_start=109
  _KEYVALUESERVICE._serialized_end=189
# @@protoc_insertion_point(module_scope)
